// Auto-generated by generate_protocol.py — DO NOT EDIT
// Generated: 2026-05-05T23:15:03.981940
// Single source of truth: Tools/protocol_defs.json

using System;

public static class MsgType
{
    // C→S Client sends player name after receiving Welcome
    public const byte JoinRoom = 0x01;
    // C→S Client sends input intent every frame (30Hz)
    public const byte PlayerInput = 0x02;
    // C→S Seeker attempts to tag a nearby hider
    public const byte TagAttempt = 0x03;
    // C→S Client signals ready in lobby
    public const byte PlayerReady = 0x04;
    // S→C Server assigns player ID and role on connect
    public const byte Welcome = 0x10;
    // S→C Server broadcasts authoritative game state transitions
    public const byte GameStateChange = 0x11;
    // S→C Server broadcasts all player positions at tick rate (30Hz)
    public const byte PlayerStates = 0x12;
    // S→C Server notifies a hider they are revealed (seeker nearby)
    public const byte Highlight = 0x13;
    // S→C Server reports result of a tag attempt
    public const byte TagResult = 0x14;
    // S→C Server sends round-end scoreboard as JSON
    public const byte ScoreBoard = 0x15;
    // S→C Server sends error code
    public const byte Error = 0x16;
}

public enum GameState : byte
{
    WaitingForPlayers = 0,
    Preparing = 1,
    Hiding = 2,
    Seeking = 3,
    RoundEnd = 4,
    GameOver = 5
}

public enum PlayerRole : byte
{
    Seeker = 0,
    Hider = 1,
    Spectator = 2
}

public struct PlayerStateEntry
{
    public byte player_id;
    public byte state;
    public float pos_x;
    public float pos_z;
    public float rot_y;
}

public static class ProtocolSerializer
{
    public static int SerializePlayerStateEntry(byte[] buf, int offset, PlayerStateEntry e)
    {
        buf[offset++] = e.player_id;
        buf[offset++] = e.state;
        System.BitConverter.GetBytes(e.pos_x).CopyTo(buf, offset); offset += 4;
        System.BitConverter.GetBytes(e.pos_z).CopyTo(buf, offset); offset += 4;
        System.BitConverter.GetBytes(e.rot_y).CopyTo(buf, offset); offset += 4;
        return 14;
    }

    public static int DeserializePlayerStateEntry(byte[] payload, int offset, out PlayerStateEntry e)
    {
        e = new PlayerStateEntry();
        e.player_id = payload[offset++];
        e.state = payload[offset++];
        e.pos_x = System.BitConverter.ToSingle(payload, offset); offset += 4;
        e.pos_z = System.BitConverter.ToSingle(payload, offset); offset += 4;
        e.rot_y = System.BitConverter.ToSingle(payload, offset); offset += 4;
        return 14;
    }

    // JoinRoom — Client sends player name after receiving Welcome
    public static byte[] SerializeJoinRoom(byte[] name)
    {
        int size = 2 + name.Length;
        byte[] buf = new byte[size];
        int offset = 0;
        buf[offset++] = MsgType.JoinRoom;
        buf[offset++] = (byte)name.Length;
        System.Buffer.BlockCopy(name, 0, buf, offset, name.Length); offset += name.Length;
        return buf;
    }

    // PlayerInput — Client sends input intent every frame (30Hz)
    public static byte[] SerializePlayerInput(float move_x, float move_z, float rot_y, byte flags)
    {
        byte[] buf = new byte[14];
        int offset = 0;
        buf[offset++] = MsgType.PlayerInput;
        System.BitConverter.GetBytes(move_x).CopyTo(buf, offset); offset += 4;
        System.BitConverter.GetBytes(move_z).CopyTo(buf, offset); offset += 4;
        System.BitConverter.GetBytes(rot_y).CopyTo(buf, offset); offset += 4;
        buf[offset++] = flags;
        return buf;
    }

    // TagAttempt — Seeker attempts to tag a nearby hider
    public static byte[] SerializeTagAttempt(byte target_id)
    {
        byte[] buf = new byte[2];
        int offset = 0;
        buf[offset++] = MsgType.TagAttempt;
        buf[offset++] = target_id;
        return buf;
    }

    public static byte[] SerializePlayerReady()
    {
        return new byte[] { MsgType.PlayerReady };
    }

    // Welcome — Server assigns player ID and role on connect
    public static byte[] SerializeWelcome(byte player_id, byte role)
    {
        byte[] buf = new byte[3];
        int offset = 0;
        buf[offset++] = MsgType.Welcome;
        buf[offset++] = player_id;
        buf[offset++] = role;
        return buf;
    }

    public static void DeserializeWelcome(byte[] payload, out byte player_id, out byte role)
    {
        player_id = default;
        role = default;
        int offset = 0;
        player_id = payload[offset++];
        role = payload[offset++];
    }

    // GameStateChange — Server broadcasts authoritative game state transitions
    public static byte[] SerializeGameStateChange(byte state, ushort countdown_sec)
    {
        byte[] buf = new byte[4];
        int offset = 0;
        buf[offset++] = MsgType.GameStateChange;
        buf[offset++] = state;
        buf[offset++] = (byte)(countdown_sec & 0xFF);
        buf[offset++] = (byte)((countdown_sec >> 8) & 0xFF);
        return buf;
    }

    public static void DeserializeGameStateChange(byte[] payload, out byte state, out ushort countdown_sec)
    {
        state = default;
        countdown_sec = default;
        int offset = 0;
        state = payload[offset++];
        countdown_sec = (ushort)(payload[offset] | (payload[offset + 1] << 8)); offset += 2;
    }

    // PlayerStates — Server broadcasts all player positions at tick rate (30Hz)
    public static byte[] SerializePlayerStates(PlayerStateEntry[] players)
    {
        int size = 2 + players.Length * 14;
        byte[] buf = new byte[size];
        int offset = 0;
        buf[offset++] = MsgType.PlayerStates;
        buf[offset++] = (byte)players.Length;
        for (int _i = 0; _i < players.Length; _i++)
        {
            offset += SerializePlayerStateEntry(buf, offset, players[_i]);
        }
        return buf;
    }

    public static void DeserializePlayerStates(byte[] payload, out PlayerStateEntry[] players)
    {
        players = null;
        int offset = 0;
        byte count = payload[offset++];
        players = new PlayerStateEntry[count];
        for (int _i = 0; _i < count; _i++)
        {
            offset += DeserializePlayerStateEntry(payload, offset, out players[_i]);
        }
    }

    // Highlight — Server notifies a hider they are revealed (seeker nearby)
    public static byte[] SerializeHighlight(byte player_id)
    {
        byte[] buf = new byte[2];
        int offset = 0;
        buf[offset++] = MsgType.Highlight;
        buf[offset++] = player_id;
        return buf;
    }

    public static void DeserializeHighlight(byte[] payload, out byte player_id)
    {
        player_id = default;
        int offset = 0;
        player_id = payload[offset++];
    }

    // TagResult — Server reports result of a tag attempt
    public static byte[] SerializeTagResult(byte seeker_id, byte target_id, byte success)
    {
        byte[] buf = new byte[4];
        int offset = 0;
        buf[offset++] = MsgType.TagResult;
        buf[offset++] = seeker_id;
        buf[offset++] = target_id;
        buf[offset++] = success;
        return buf;
    }

    public static void DeserializeTagResult(byte[] payload, out byte seeker_id, out byte target_id, out byte success)
    {
        seeker_id = default;
        target_id = default;
        success = default;
        int offset = 0;
        seeker_id = payload[offset++];
        target_id = payload[offset++];
        success = payload[offset++];
    }

    // ScoreBoard — Server sends round-end scoreboard as JSON
    public static byte[] SerializeScoreBoard(byte[] json)
    {
        int size = 1 + json.Length;
        byte[] buf = new byte[size];
        int offset = 0;
        buf[offset++] = MsgType.ScoreBoard;
        System.Buffer.BlockCopy(json, 0, buf, offset, json.Length); offset += json.Length;
        return buf;
    }

    public static void DeserializeScoreBoard(byte[] payload, out byte[] json)
    {
        json = null;
        int offset = 0;
        json = new byte[payload.Length - offset];
        System.Buffer.BlockCopy(payload, offset, json, 0, json.Length);
    }

    // Error — Server sends error code
    public static byte[] SerializeError(byte code)
    {
        byte[] buf = new byte[2];
        int offset = 0;
        buf[offset++] = MsgType.Error;
        buf[offset++] = code;
        return buf;
    }

    public static void DeserializeError(byte[] payload, out byte code)
    {
        code = default;
        int offset = 0;
        code = payload[offset++];
    }

}