// Auto-generated by generate_protocol.py — DO NOT EDIT
// Generated: 2026-05-05T23:15:03.963401
// Single source of truth: Tools/protocol_defs.json

#pragma once

#include "enet.h"
#include <cstdint>
#include <cstring>
#include <string>

constexpr int SERVER_TICK_STEP_MS = 33;
constexpr int SERVER_PORT = 9000;
constexpr int MAX_PLAYERS = 7;

constexpr int ENET_CHANNELS = 2;
constexpr int ENET_CH_RELIABLE = 0;
constexpr int ENET_CH_UNRELIABLE = 1;

enum class GameState : uint8_t {
    WaitingForPlayers = 0,
    Preparing = 1,
    Hiding = 2,
    Seeking = 3,
    RoundEnd = 4,
    GameOver = 5
};

enum class PlayerRole : uint8_t {
    Seeker = 0,
    Hider = 1,
    Spectator = 2
};

enum class PlayerState : uint8_t {
    Normal = 0,
    Crouching = 1,
    Stunned = 2,
    Caught = 3
};

namespace MsgType {
    constexpr uint8_t JoinRoom = 0x01;
    constexpr uint8_t PlayerInput = 0x02;
    constexpr uint8_t TagAttempt = 0x03;
    constexpr uint8_t PlayerReady = 0x04;
    constexpr uint8_t Welcome = 0x10;
    constexpr uint8_t GameStateChange = 0x11;
    constexpr uint8_t PlayerStates = 0x12;
    constexpr uint8_t Highlight = 0x13;
    constexpr uint8_t TagResult = 0x14;
    constexpr uint8_t ScoreBoard = 0x15;
    constexpr uint8_t Error = 0x16;
}

struct Player;

struct PlayerStateEntry {
    uint8_t player_id;
    uint8_t state;
    float pos_x;
    float pos_z;
    float rot_y;
};

inline size_t serialize_PlayerStateEntry(uint8_t* buf, const PlayerStateEntry& e) {
    size_t off = 0;
    buf[off++] = e.player_id;
    buf[off++] = e.state;
    memcpy(&buf[off], &e.pos_x, 4); off += 4;
    memcpy(&buf[off], &e.pos_z, 4); off += 4;
    memcpy(&buf[off], &e.rot_y, 4); off += 4;
    return off;
}

inline size_t deserialize_PlayerStateEntry(const uint8_t* data, size_t max_len, PlayerStateEntry& e) {
    size_t off = 0;
    e.player_id = data[off++];
    e.state = data[off++];
    memcpy(&e.pos_x, &data[off], 4); off += 4;
    memcpy(&e.pos_z, &data[off], 4); off += 4;
    memcpy(&e.rot_y, &data[off], 4); off += 4;
    return off;
}

// ═══ Message serialization (build_xxx / parse_xxx) ═══

// JoinRoom (client→to→server) — Client sends player name after receiving Welcome
inline size_t build_JoinRoom(uint8_t* buf, const std::string& name) {
    size_t off = 0;
    buf[off++] = MsgType::JoinRoom;
    buf[off++] = static_cast<uint8_t>(name.size());
    memcpy(&buf[off], name.data(), name.size()); off += name.size();
    return off;
}

inline bool parse_JoinRoom(const uint8_t* data, size_t max_len, std::string& out_name) {
    size_t off = 0;
    uint8_t _name_len = data[off++];
    // (used by downstream field)
    std::string _name(reinterpret_cast<const char*>(&data[off]), _name_len); off += _name_len;
    out_name = std::move(_name);
    return true;
}

// PlayerInput (client→to→server) — Client sends input intent every frame (30Hz)
inline size_t build_PlayerInput(uint8_t* buf, float move_x, float move_z, float rot_y, uint8_t flags) {
    size_t off = 0;
    buf[off++] = MsgType::PlayerInput;
    memcpy(&buf[off], &move_x, 4); off += 4;
    memcpy(&buf[off], &move_z, 4); off += 4;
    memcpy(&buf[off], &rot_y, 4); off += 4;
    buf[off++] = flags;
    return off;
}

inline bool parse_PlayerInput(const uint8_t* data, size_t max_len, float& out_move_x, float& out_move_z, float& out_rot_y, uint8_t& out_flags) {
    size_t off = 0;
    float _move_x; memcpy(&_move_x, &data[off], 4); off += 4;
    out_move_x = _move_x;
    float _move_z; memcpy(&_move_z, &data[off], 4); off += 4;
    out_move_z = _move_z;
    float _rot_y; memcpy(&_rot_y, &data[off], 4); off += 4;
    out_rot_y = _rot_y;
    uint8_t _flags = data[off++];
    out_flags = _flags;
    return true;
}

// TagAttempt (client→to→server) — Seeker attempts to tag a nearby hider
inline size_t build_TagAttempt(uint8_t* buf, uint8_t target_id) {
    size_t off = 0;
    buf[off++] = MsgType::TagAttempt;
    buf[off++] = target_id;
    return off;
}

inline bool parse_TagAttempt(const uint8_t* data, size_t max_len, uint8_t& out_target_id) {
    size_t off = 0;
    uint8_t _target_id = data[off++];
    out_target_id = _target_id;
    return true;
}

// PlayerReady (client→to→server) — Client signals ready in lobby
inline size_t build_PlayerReady(uint8_t* buf) {
    size_t off = 0;
    buf[off++] = MsgType::PlayerReady;
    return off;
}

inline bool parse_PlayerReady(const uint8_t* data, size_t max_len) {
    size_t off = 0;
    return true;
}

// Welcome (server→to→client) — Server assigns player ID and role on connect
inline size_t build_Welcome(uint8_t* buf, uint8_t player_id, uint8_t role) {
    size_t off = 0;
    buf[off++] = MsgType::Welcome;
    buf[off++] = player_id;
    buf[off++] = role;
    return off;
}

inline bool parse_Welcome(const uint8_t* data, size_t max_len, uint8_t& out_player_id, uint8_t& out_role) {
    size_t off = 0;
    uint8_t _player_id = data[off++];
    out_player_id = _player_id;
    uint8_t _role = data[off++];
    out_role = _role;
    return true;
}

// GameStateChange (server→to→client) — Server broadcasts authoritative game state transitions
inline size_t build_GameStateChange(uint8_t* buf, uint8_t state, uint16_t countdown_sec) {
    size_t off = 0;
    buf[off++] = MsgType::GameStateChange;
    buf[off++] = state;
    buf[off++] = static_cast<uint8_t>(countdown_sec & 0xFF);
    buf[off++] = static_cast<uint8_t>((countdown_sec >> 8) & 0xFF);
    return off;
}

inline bool parse_GameStateChange(const uint8_t* data, size_t max_len, uint8_t& out_state, uint16_t& out_countdown_sec) {
    size_t off = 0;
    uint8_t _state = data[off++];
    out_state = _state;
    uint16_t _countdown_sec = static_cast<uint16_t>(data[off]) | (static_cast<uint16_t>(data[off+1]) << 8); off += 2;
    out_countdown_sec = _countdown_sec;
    return true;
}

// PlayerStates (server→to→client) — Server broadcasts all player positions at tick rate (30Hz)
inline size_t build_PlayerStates(uint8_t* buf, const PlayerStateEntry* players, uint8_t count) {
    size_t off = 0;
    buf[off++] = MsgType::PlayerStates;
    buf[off++] = count;
    for (uint8_t _i = 0; _i < count; _i++) {
        off += serialize_PlayerStateEntry(&buf[off], players[_i]);
    }
    return off;
}

inline bool parse_PlayerStates(const uint8_t* data, size_t max_len, PlayerStateEntry* out_players, uint8_t& out_count) {
    size_t off = 0;
    uint8_t _count = data[off++];
    // (used by downstream field)
    out_count = _count;
    // element deserialization handled by caller (variable-size)
    return true;
}

// Highlight (server→to→client) — Server notifies a hider they are revealed (seeker nearby)
inline size_t build_Highlight(uint8_t* buf, uint8_t player_id) {
    size_t off = 0;
    buf[off++] = MsgType::Highlight;
    buf[off++] = player_id;
    return off;
}

inline bool parse_Highlight(const uint8_t* data, size_t max_len, uint8_t& out_player_id) {
    size_t off = 0;
    uint8_t _player_id = data[off++];
    out_player_id = _player_id;
    return true;
}

// TagResult (server→to→client) — Server reports result of a tag attempt
inline size_t build_TagResult(uint8_t* buf, uint8_t seeker_id, uint8_t target_id, uint8_t success) {
    size_t off = 0;
    buf[off++] = MsgType::TagResult;
    buf[off++] = seeker_id;
    buf[off++] = target_id;
    buf[off++] = success;
    return off;
}

inline bool parse_TagResult(const uint8_t* data, size_t max_len, uint8_t& out_seeker_id, uint8_t& out_target_id, uint8_t& out_success) {
    size_t off = 0;
    uint8_t _seeker_id = data[off++];
    out_seeker_id = _seeker_id;
    uint8_t _target_id = data[off++];
    out_target_id = _target_id;
    uint8_t _success = data[off++];
    out_success = _success;
    return true;
}

// ScoreBoard (server→to→client) — Server sends round-end scoreboard as JSON
inline size_t build_ScoreBoard(uint8_t* buf, const std::string& json) {
    size_t off = 0;
    buf[off++] = MsgType::ScoreBoard;
    memcpy(&buf[off], json.data(), json.size()); off += json.size();
    return off;
}

inline bool parse_ScoreBoard(const uint8_t* data, size_t max_len, std::string& out_json) {
    size_t off = 0;
    std::string _json(reinterpret_cast<const char*>(&data[off]), max_len - (off));
    out_json = std::move(_json);
    return true;
}

// Error (server→to→client) — Server sends error code
inline size_t build_Error(uint8_t* buf, uint8_t code) {
    size_t off = 0;
    buf[off++] = MsgType::Error;
    buf[off++] = code;
    return off;
}

inline bool parse_Error(const uint8_t* data, size_t max_len, uint8_t& out_code) {
    size_t off = 0;
    uint8_t _code = data[off++];
    out_code = _code;
    return true;
}

// ═══ Convenience send wrappers (allocate ENetPacket + send) ═══

inline void send_Welcome(ENetPeer* peer, uint8_t player_id, uint8_t role) {
    uint8_t buf[256];
    size_t len = build_Welcome(buf, player_id, role);
    ENetPacket* pkt = enet_packet_create(buf, len, ENET_PACKET_FLAG_RELIABLE);
    enet_peer_send(peer, ENET_CH_RELIABLE, pkt);
}

inline void send_GameStateChange(ENetPeer* peer, uint8_t state, uint16_t countdown_sec) {
    uint8_t buf[256];
    size_t len = build_GameStateChange(buf, state, countdown_sec);
    ENetPacket* pkt = enet_packet_create(buf, len, ENET_PACKET_FLAG_RELIABLE);
    enet_peer_send(peer, ENET_CH_RELIABLE, pkt);
}

inline void send_PlayerStates(ENetHost* host, const Player* players, size_t count) {
    uint8_t buf[2 + MAX_PLAYERS * 14];
    size_t off = 0;
    buf[off++] = MsgType::PlayerStates;
    size_t cnt_off = off++;
    uint8_t actual = 0;
    for (size_t i = 0; i < count; i++) {
        if (!players[i].connected || players[i].peer == nullptr) continue;
        buf[off++] = players[i].id;
        buf[off++] = static_cast<uint8_t>(players[i].state);
        memcpy(&buf[off], &players[i].pos_x, 4); off += 4;
        memcpy(&buf[off], &players[i].pos_z, 4); off += 4;
        memcpy(&buf[off], &players[i].rot_y, 4); off += 4;
        actual++;
    }
    if (actual == 0) return;
    buf[cnt_off] = actual;
    ENetPacket* pkt = enet_packet_create(buf, off, ENET_PACKET_FLAG_UNSEQUENCED);
    enet_host_broadcast(host, ENET_CH_UNRELIABLE, pkt);
}

inline void send_Highlight(ENetPeer* peer, uint8_t player_id) {
    uint8_t buf[256];
    size_t len = build_Highlight(buf, player_id);
    ENetPacket* pkt = enet_packet_create(buf, len, ENET_PACKET_FLAG_RELIABLE);
    enet_peer_send(peer, ENET_CH_RELIABLE, pkt);
}

inline void send_TagResult(ENetPeer* peer, uint8_t seeker_id, uint8_t target_id, uint8_t success) {
    uint8_t buf[256];
    size_t len = build_TagResult(buf, seeker_id, target_id, success);
    ENetPacket* pkt = enet_packet_create(buf, len, ENET_PACKET_FLAG_RELIABLE);
    enet_peer_send(peer, ENET_CH_RELIABLE, pkt);
}

inline void send_ScoreBoard(ENetPeer* peer, const std::string& json) {
    uint8_t buf[256];
    size_t len = build_ScoreBoard(buf, json);
    ENetPacket* pkt = enet_packet_create(buf, len, ENET_PACKET_FLAG_RELIABLE);
    enet_peer_send(peer, ENET_CH_RELIABLE, pkt);
}

inline void send_Error(ENetPeer* peer, uint8_t code) {
    uint8_t buf[256];
    size_t len = build_Error(buf, code);
    ENetPacket* pkt = enet_packet_create(buf, len, ENET_PACKET_FLAG_RELIABLE);
    enet_peer_send(peer, ENET_CH_RELIABLE, pkt);
}
